# Generated by Django 5.2 on 2025-05-17 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_experience_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject', models.CharField(help_text='A brief summary or title of the notification.', max_length=255)),
                ('message', models.TextField(help_text='The main content or details of the notification.')),
                ('notification_type', models.CharField(blank=True, help_text="Optional category for the notification (e.g., 'new_feature', 'announcement').", max_length=50, null=True)),
                ('link', models.URLField(blank=True, help_text='Optional URL associated with this notification.', null=True)),
                ('sender', models.ForeignKey(blank=True, help_text='The admin or teacher who created this notification (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notification')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(help_text='Select one or more users to receive this notification.', related_name='notifications', through='users.NotificationRecipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
