# Generated by Django 5.1.3 on 2025-05-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_notification_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='level',
        ),
    ]
