# Generated by Django 5.1.3 on 2025-06-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_create_default_org_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrecipient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
