# Generated by Django 5.1.3 on 2025-05-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_video_remove_knowledgetrail_is_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='module',
        ),
        migrations.RemoveField(
            model_name='watchedvideo',
            name='video',
        ),
        migrations.RemoveField(
            model_name='watchedvideo',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='WatchedVideo',
        ),
    ]
