# Generated by Django 5.1.3 on 2025-05-19 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_remove_module_course_remove_certificate_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text="The correct answer for 'fill in the gap' questions.", null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='typed_answer',
            field=models.TextField(blank=True, help_text="The student's answer for 'fill in the gap' questions.", null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.option'),
        ),
    ]
