# Generated by Django 5.1.3 on 2025-05-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_question_correct_answer_studentanswer_typed_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgetrail',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='knowledgetrail',
            name='media_type',
        ),
        migrations.AddField(
            model_name='knowledgetrail',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='knowledge_pdf_media/'),
        ),
        migrations.AddField(
            model_name='knowledgetrail',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='knowledge_video_media/'),
        ),
    ]
