# Generated by Django 5.1.3 on 2025-05-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_remove_knowledgetrail_media_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='max_score',
        ),
        migrations.AddField(
            model_name='game',
            name='played_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgetrail',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgetrail',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('fill_in_the_blank', 'Fill in the blank'), ('drag_and_drop', 'Drag and drop'), ('match_the_column', 'Match the column'), ('word_hunt', 'Word hunt')], default='quiz', help_text='The type of question (e.g., quit, fill in the blank etc).', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='typed_answer',
            field=models.TextField(blank=True, help_text="The student's answer for 'fill in the blank' questions.", null=True),
        ),
    ]
