# Generated by Django 5.1.3 on 2025-05-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_remove_game_description_remove_game_max_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.IntegerField(default=0)),
                ('teachers', models.IntegerField(default=0)),
                ('knowledge_trail_videos', models.IntegerField(default=0)),
                ('knowledge_trail_pdfs', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
