# Generated by Django 5.1.3 on 2025-06-04 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_statistics_certificates_issued_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgetrail',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If True, all students can see this. If False, only selected students can see it.'),
        ),
        migrations.AddField(
            model_name='knowledgetrail',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order within the module'),
        ),
        migrations.AddField(
            model_name='knowledgetrail',
            name='target_students',
            field=models.ManyToManyField(blank=True, help_text='Specific students who can see this knowledge trail when not public', related_name='targeted_knowledge_trails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Correct order for matching/arranging type games.', null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this module appears')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.subject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='knowledgetrail',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_trails', to='learning.module'),
        ),
    ]
